#!/bin/bash
# Fix: Show SSH Targets instead of Tunnels in Remote Explorer
# The Remote Explorer can show different views - we need to switch to "SSH Targets"

echo "================================================"
echo "  Fix: VS Code Remote Explorer - Switch View"
echo "================================================"
echo ""
echo "PROBLEM: You see 'Tunnels' but not 'b2b'"
echo ""
echo "SOLUTION: Change the Remote Explorer dropdown"
echo ""
echo "========== STEP-BY-STEP =========="
echo ""
echo "1. Look at the REMOTE EXPLORER panel (left sidebar)"
echo ""
echo "2. At the TOP of that panel, find the DROPDOWN"
echo "   (Currently shows 'Tunnels')"
echo ""
echo "3. CLICK the dropdown arrow/button"
echo ""
echo "4. SELECT: 'SSH Targets' from the menu"
echo ""
echo "5. NOW you should see 'b2b' listed below"
echo ""
echo "========== ALTERNATIVE METHOD =========="
echo ""
echo "If the dropdown doesn't work, use this command:"
echo ""
echo "  Ctrl+Shift+P → type: Remote-SSH: Connect to Host..."
echo "  → Select 'b2b' or type: b2b"
echo ""
echo "========== VERIFY SSH CONFIG =========="
echo ""
ssh -G b2b 2>/dev/null | head -10
echo ""
echo "========== TEST SSH CONNECTION =========="
echo ""
ssh -v b2b echo "✓ SSH works!" 2>&1 | grep -E "(Authenticated|ssh.*exec|✓)" | head -3
echo ""
